-- Database Schema for VinylVerse Order Processing Microservice
-- This schema supports persisting customer orders, shipping info, payment info, and line items

-- ITEM table (inventory management - referenced by order processing)
-- This table should be created by the inventory-management microservice
-- Included here for reference
CREATE TABLE IF NOT EXISTS ITEM (
    ITEM_NUMBER VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10, 2) NOT NULL,
    AVAILABLE_QUANTITY INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- SHIPPING_INFO table
-- Stores shipping address information for orders
CREATE TABLE IF NOT EXISTS SHIPPING_INFO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ADDRESS1 VARCHAR(255) NOT NULL,
    ADDRESS2 VARCHAR(255),
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL DEFAULT 'USA',
    POSTAL_CODE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT_INFO table
-- Stores masked payment information (card number is masked, only last 4 digits stored)
CREATE TABLE IF NOT EXISTS PAYMENT_INFO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    HOLDER_NAME VARCHAR(255) NOT NULL,
    CARD_NUM VARCHAR(50) NOT NULL, -- Masked format: "**** **** **** 1234"
    EXP_DATE VARCHAR(10), -- Format: "MM/YY"
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CUSTOMER_ORDER table
-- Main order table that links customer, shipping, and payment information
CREATE TABLE IF NOT EXISTS CUSTOMER_ORDER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(255),
    SHIPPING_INFO_ID_FK INT NOT NULL,
    PAYMENT_INFO_ID_FK INT NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    CONFIRMATION_ID VARCHAR(100) UNIQUE NOT NULL, -- Format: "ORD-{timestamp}-{hex}"
    STATUS VARCHAR(50) DEFAULT 'CONFIRMED',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SHIPPING_INFO_ID_FK) REFERENCES SHIPPING_INFO(ID) ON DELETE RESTRICT,
    FOREIGN KEY (PAYMENT_INFO_ID_FK) REFERENCES PAYMENT_INFO(ID) ON DELETE RESTRICT,
    INDEX idx_confirmation_id (CONFIRMATION_ID),
    INDEX idx_customer_email (CUSTOMER_EMAIL),
    INDEX idx_created_at (CREATED_AT)
);

-- CUSTOMER_ORDER_LINE_ITEM table
-- Stores individual items within an order
CREATE TABLE IF NOT EXISTS CUSTOMER_ORDER_LINE_ITEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_NUMBER VARCHAR(50) NOT NULL,
    ITEM_NAME VARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    CUSTOMER_ORDER_ID_FK INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ORDER_ID_FK) REFERENCES CUSTOMER_ORDER(ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM_NUMBER) REFERENCES ITEM(ITEM_NUMBER) ON DELETE RESTRICT,
    INDEX idx_order_id (CUSTOMER_ORDER_ID_FK),
    INDEX idx_item_number (ITEM_NUMBER)
);

-- Sample data for testing (optional)
-- INSERT INTO ITEM (ITEM_NUMBER, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY) VALUES
-- ('1', 'Pink Floyd - The Dark Side of the Moon', 'Original 1973 pressing', 24.99, 10),
-- ('2', 'The Beatles - Abbey Road', 'Anniversary Edition LP', 22.99, 15),
-- ('3', 'Prince - Purple Rain', 'Limited Edition 40th Anniversary', 29.99, 8),
-- ('4', 'Michael Jackson - Thriller', '25th Anniversary Edition', 19.99, 12);

